name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # ワークフローを手動で実行できるように追加

jobs:
  build:
    runs-on: ubuntu-24.04 # ubuntu-latestからubuntu-24.04に変更

    outputs:
      is_act: ${{ steps.check_act.outputs.is_act }}

    steps:
    - name: リポジトリのチェックアウト # ステップ名を日本語化
      uses: actions/checkout@v4

    - name: actでの実行を判別 # actでの実行かどうかを判別
      id: check_act
      run: |
        if [ -n "${{ env.ACT }}" ]; then
          echo "::notice::actで実行されています。"
          echo "is_act=true" >> $GITHUB_OUTPUT
        else
          echo "::notice::GitHub Actionsで実行されています。"
          echo "is_act=false" >> $GITHUB_OUTPUT
        fi

    - name: Docker向けQEMUのセットアップ # マルチアーキテクチャビルドのためにQEMUをセットアップ
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Docker Buildxのセットアップ # ステップ名を日本語化
      uses: docker/setup-buildx-action@v3

    - name: Dockerログイン (ghcr.io) # actではない場合のみghcr.ioにログイン
      if: ${{ steps.check_act.outputs.is_act == 'false' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 日付タグの生成 # 日本時間を基準とした日付タグを生成
      id: generate_tag
      run: |
        echo "DATE_TAG=$(TZ='Asia/Tokyo' date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

    - name: マルチプラットフォームDockerイメージのビルド # ステップ名を日本語化
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ steps.check_act.outputs.is_act == 'false' }} # actではない場合はプッシュ
        load: ${{ steps.check_act.outputs.is_act == 'true' }} # actの場合はロード
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.generate_tag.outputs.DATE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
